version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      # copy the build artifacts to an S3 bucket
      - aws s3 sync build/* s3://vaibhavraj.sheerhsjain.live
