name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: creating the npm
      run: yarn install
    
    - name: artifact build
      run: yar build 
    
    #- name: pushing to github
    
